# Generated by Django 5.0.3 on 2024-03-09 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('femail', 'FEMAIL')], max_length=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RelationShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_type', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('wife', 'Wife')], max_length=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('first_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_set', to='relation.persondetail')),
                ('second_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_set', to='relation.persondetail')),
            ],
        ),
    ]
